services:
  static-web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - PORT=3000

networks:
  app-network:
    driver: bridge
